spring:
  jackson:
    default-property-inclusion: non_null
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    base-url: http://localhost:8003
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8002/eureka/
hystrix:
  shareSecurityContext: true
signing:
  key: "345345fsdfsf534243asd"